# Generated by Django 4.2 on 2023-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_categoryname_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_counter',
            field=models.IntegerField(default=0),
        ),
    ]
